strictPeerDependencies: false
packageLock: true

overrides:
  compare-func: ^2.0.0
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  esbuild@<=0.24.2: '>=0.25.0'
  undici@<5.29.0: '>=5.29.0'
  tar@=7.5.1: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
