name = "onebot-status-helper"
# 默认为 Production 环境
main = "dist/cloudflare-workers.mjs"
minify = true
compatibility_date = "2025-10-30"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "public" }

[vars]
# 超时时间(ms)
TIMEOUT = 60000
# 最大请求体大小(字节)，默认 100MB
MAX_BODY_SIZE = 104857600

[env.dev]
# Development 环境配置
main = "src/cloudflare-workers.ts"
minify = false
assets = { directory = "public" }

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
